name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_PUSHER_KEY: ${{ secrets.NEXT_PUBLIC_PUSHER_KEY }}
          NEXT_PUBLIC_PUSHER_CLUSTER: ${{ secrets.NEXT_PUBLIC_PUSHER_CLUSTER }}
          NEXT_PUBLIC_SOKETI_HOST: ${{ secrets.NEXT_PUBLIC_SOKETI_HOST }}
          NEXT_PUBLIC_SOKETI_PORT: ${{ secrets.NEXT_PUBLIC_SOKETI_PORT }}
          NEXT_PUBLIC_SOKETI_TLS: ${{ secrets.NEXT_PUBLIC_SOKETI_TLS }}
          NEXT_PUBLIC_SOKETI_PATH: ${{ secrets.NEXT_PUBLIC_SOKETI_PATH }}

      - name: Package Deployment Files
        run: zip -r deploy.zip .next public package.json pnpm-lock.yaml pnpm-workspace.yaml prisma

      - name: Copy Files to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          port: ${{ vars.VPS_PORT }}
          source: "deploy.zip"
          target: ${{ vars.PROJECT_PATH }}

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          port: ${{ vars.VPS_PORT }}
          script: |
            echo "üîß Loading NVM..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            echo "üìÅ Navigating to project directory..."
            cd ${{ vars.PROJECT_PATH }}

            echo "üì¶ Unzipping new version..."
            unzip -o deploy.zip

            echo "üßπ Installing --prod dependencies..."
            pnpm install --prod

            echo "üóÑÔ∏è Running database migrations..."
            pnpm prisma:deploy

            echo "üîÑ Reloading application..."
            pm2 reload ${{ vars.PM2_APP_NAME }}

            echo "üóëÔ∏è Cleaning up..."
            rm deploy.zip

            echo "‚úÖ Deployment finished."
